#!/bin/sh                                                   
rm db/dump/dump.sql.gz
mysqldump -uroot gwap2_take2_development > db/dump/dump.sql
gzip db/dump/dump.sql
rm db/dump.*
hdiutil create -encryption -stdinpass -srcfolder db/dump/ db/dump.dmg
