#!/usr/bin/env ruby

# this script has nothing to do with GWAP2, really, but it needs to be somewhere

# it is used to correct weights.eda files generated by inferelator with the old "activates" syntax for edges that have negative values

if ARGV.size != 2
  puts "supply filenames for weights.eda and network.sif files"
  exit
end
   
nf = File.open(ARGV[1])                                                      
net = {}
while(line = nf.gets)
  src,type,dest = line.chomp.split(" ")  # only works if there are no orphans
  net[[src,dest]] = type
end


f = File.open(ARGV.first)
while (line = f.gets)
  if line =~ / -/
    line.gsub!(/ -/, " ")
    line.gsub!(/activates/, "represses")
    src,type,dest,eq,weight = line.chomp.split(" ")
    net[[src,dest]] = "represses"
  end
  puts line
end


wn = File.open("newnetwork.sif", "w")
net.each_pair do |k,v|
  wn.puts "#{k.first} #{v} #{k.last}"
end