#!/usr/bin/env ruby

# this script has nothing to do with GWAP2, really, but it needs to be somewhere

# it is used to correct weights.eda files generated by inferelator with the old "activates" syntax for edges that have negative values

if ARGV.empty?
  puts "supply a filename for your weights.eda file"
  exit
end


f = File.open(ARGV.first)
while (line = f.gets)
  if line =~ / -/
    line.gsub!(/ -/, " ")
    line.gsub!(/activates/, "represses")
  end
  puts line
end